#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         2.5
bspc config window_gap          11

bspc config active_border_color \#ffffff
bspc config normal_border_color \#747474
bspc config focused_border_color \#ffffff

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^3'
